spring:
  profiles:
    active: dev
  application:
    name: yupao-backend
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yupao?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  #session 失效时间(分钟)
  session:
    timeout: 1
    store-type: redis
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #redis 配置
  redis:
    port: 6379
    host: localhost
    database: 2

server:
  port: 8081
  servlet:
    context-path: /api
    session:
      timeout: 1
#      cookie:
#        domain: 101.133.136.159
#        secure: true
#        same-site: none
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    db-config:
      timezone: GMT+8
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
